export const GET_POSTS = 'get_posts'
export const ADD_NEWSLETTER = 'add_newsletter'
export const CLEAR_NEWSLETTER = 'clear_newsletter'
export const GET_POSTS_BY_ID = 'get_posts_by_id'
export const CLEAR_POSTS_BY_ID = 'clear_posts_by_id'